/*
 * generated by Xtext 2.17.1
 */
package circus.robocalc.robochart.assertions.ide


/**
 * Use this class to register ide components.
 */
class AssertionsIdeModule extends AbstractAssertionsIdeModule {
}
